[package]
name = "external-server-a"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
external-server = { path = "../external-server" }
capnp = "0.10"
