[package]
name = "armour-master"
version = "0.3.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"
#default-run = "armour-master"
#
#[[bin]]
#name = "armour-master"
#path = "src/main.rs"
#
#[[bin]]
#name = "client"
#path = "src/client.rs"

[dependencies]
armour-api = { path = "../armour-api" }
armour-lang = { path = "../armour-lang" }
armour-serde = { path = "../armour-serde" }

actix = "0.9"
actix-rt = "1.1"
actix-web = "2.0"
argon2rs = "0.2"
base64 = "0.12"
bytes = "0.5"
clap = "2.33"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.3"
rpassword = "4.0"
rustyline = "6.1"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["uds", "tcp"] }
tokio-util = { version = "0.2", features = ["codec"] }
url = "2.1"
