### armour-host:> launch log

### succeed
GET https://localhost:8090/host/label HTTP/1.1

### succeed
GET https://localhost:8090/host/proxies HTTP/1.1

### succeed
GET https://localhost:8090/policy/query HTTP/1.1
content-type: application/json

"proxy"

### succeed
POST https://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "proxy",
  "policy": {
    "HTTP": "H4sIAAAAAAAE/12JQQ4AEAwEhR/wQHFwE0WJ79s9atOZZrfOTDCZ0VMgAm5pTW5eVTc0Dy7bRIHvq0O6VrTuAQFfiT9pAAAA",
    "TCP": "H4sIAAAAAAAE/12JUQoAIAxCo04QdL+I1UcQW1DQ9Zv1N/EJqjMKpqN6hJIUuIwhJ2+amYS50e7C2CNCEX5n7Yv+r5u70UHOrWkAAAA="
  }
}

### fail (no matches)
POST https://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "other",
  "policy": {
    "HTTP": "H4sIAAAAAAAE/12JQQ4AEAwEhR/wQHFwE0WJ79s9atOZZrfOTDCZ0VMgAm5pTW5eVTc0Dy7bRIHvq0O6VrTuAQFfiT9pAAAA",
    "TCP": "H4sIAAAAAAAE/12JUQoAIAxCo04QdL+I1UcQW1DQ9Zv1N/EJqjMKpqN6hJIUuIwhJ2+amYS50e7C2CNCEX5n7Yv+r5u70UHOrWkAAAA="
  }
}

### fail (not valid base64)
POST https://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "myproxy",
  "policy": {
    "HTTP": "AA=",
    "TCP": "AA="
  }
}
