### armour-master:> myproxy: launch log

### succeed
GET http://localhost:8090/master/label HTTP/1.1

### succeed
GET http://localhost:8090/master/proxies HTTP/1.1

### succeed
GET http://localhost:8090/policy/query HTTP/1.1
content-type: application/json

"myproxy"

### succeed
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "myproxy",
  "policy": {
    "HTTP": "H4sIAAAAAAAE/12JQQ4AEAwEhR/wQHFwE0WJ79s9atOZZrfOTDCZ0VMgAm5pTW5eVTc0Dy7bRIHvq0O6VrTuAQFfiT9pAAAA",
    "TCP": "H4sIAAAAAAAE/12JUQoAIAxCo04QdL+I1UcQW1DQ9Zv1N/EJqjMKpqN6hJIUuIwhJ2+amYS50e7C2CNCEX5n7Yv+r5u70UHOrWkAAAA="
  }
}

### fail (no matches)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "other",
  "policy": {
    "HTTP": "H4sIAAAAAAAE/12JQQ4AEAwEhR/wQHFwE0WJ79s9atOZZrfOTDCZ0VMgAm5pTW5eVTc0Dy7bRIHvq0O6VrTuAQFfiT9pAAAA",
    "TCP": "H4sIAAAAAAAE/12JUQoAIAxCo04QdL+I1UcQW1DQ9Zv1N/EJqjMKpqN6hJIUuIwhJ2+amYS50e7C2CNCEX5n7Yv+r5u70UHOrWkAAAA="
  }
}

### fail (not valid base64)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "myproxy",
  "policy": {
    "HTTP": "AA=",
    "TCP": "AA="
  }
}
