[package]
name = "server"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
actix  = "0.8"
actix-web = "1.0"
clap = "2.33"
log = "0.4"
pretty_env_logger = "0.3"
