apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: client
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: client
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: server
---
apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: client
  labels:
    app: client
spec:
  containers:
  - name: client
    image: nginx
    ports:
    - containerPort: 80
