[package]
name = "armour-data-interface"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
actix = "0.8"
serde = { version = "1.0",  features = ["derive"] }
bytes = "0.4"
byteorder = "1.3"
bincode = "1.1"
tokio-io = "0.1"
