Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "arm-demo"
  config.vm.define "arm-demo"
  config.vm.provider :virtualbox do |vb|
    vb.name = "arm-demo"
    vb.memory = 4096
    vb.cpus = 2
  end 
  config.vm.provision :docker
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y build-essential qemu-system-arm unzip
  SHELL
  config.vm.provision "file", source: "../../src", destination: "$HOME/src"
  config.vm.provision "file", source: "build", destination: "$HOME/build"
  config.vm.provision "file", source: "rpi", destination: "$HOME/rpi"
  config.vm.provision "file", source: "../data-plane", destination: "$HOME/data-plane"
  config.vm.provision "file", source: "Dockerfile", destination: "$HOME/Dockerfile"
  config.vm.provision "file", source: "../server", destination: "$HOME/server"
end
