[package]
name = "logger"
version = "0.2.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot = { path = "../dot-rust" }
policy-service = { path = "../policy-service" }

actix = "0.9"
actix-files = "0.2"
actix-rt = "1.1"
actix-web = "2.0"
capnp = "0.13"
chrono = {version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
futures = "0.3"
log = "0.4"
petgraph = "0.5"
pretty_env_logger = "0.4"
rustyline = "6.2"
serde = { version = "1.0",  features = ["derive"] }
serde_yaml = "0.8"
v_htmlescape = "0.4"
