[package]
name = "logger"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
external-server = { path = "../external-server" }
capnp = "0.10"
futures = "0.1"
tokio = "0.1"
tokio-signal = "0.2"
