version: "3.0"
services:
  server:
    container_name: server
    hostname: server
    build: ..
    image: armour-examples
    command: python server.py
    volumes:
      - ../server/:/app
    expose:
      - "8080"
    extra_hosts:
      - "client-1:172.19.0.2"
      - "client-2:172.20.0.2"
    networks:
      srv-net:
        ipv4_address: 172.18.0.2

  client-1:
    container_name: client-1
    hostname: client-1
    build: ..
    image: armour-examples
    tty: true
    extra_hosts:
      - "server:172.18.0.2"
      - "client-2:172.20.0.2"
    networks:
      cl-net-1:
        ipv4_address: 172.19.0.2

  client-2:
    container_name: client-2
    hostname: client-2
    build: ..
    image: armour-examples
    tty: true
    extra_hosts:
      - "client-1:172.19.0.2"
      - "server:172.18.0.2"
    networks:
      cl-net-2:
        ipv4_address: 172.20.0.2

networks:
  cl-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/28

  cl-net-2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-2
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/28

  srv-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net
    ipam:
      config:
        - subnet: 172.18.0.0/28
