[package]
name = "armour-launch"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
armour-compose = { path = "../armour-compose" }

serde = { version = "1.0",  features = ["derive"] }
clap = "2.33"
serde_yaml = "0.8"
actix-rt = "1.0"
awc = "1.0.1"
shiplift = "0.6.0"
tokio = "0.1"