[package]
name = "armour-launch"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
armour-api = { path = "../armour-api" }
armour-compose = { path = "../armour-compose" }
docker-api = { path = "../docker-api" }

clap = "2.33"
serde_yaml = "0.8"
actix-rt = "1.0"
awc = "1.0.1"