[package]
name = "armour-launch"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
armour-compose = { path = "../armour-compose" }

serde = { version = "1.0",  features = ["derive"] }
clap = "2.33"
serde_yaml = "0.8"
serde_json = "1.0"
actix-web = "2.0"
actix-rt = "1.0"
awc = "1.0.1"
futures = "0.1"
actix = "0.9.0"
actix-codec = "0.2.0"
bytes = "0.5.4"
shiplift = "0.6.0"
regex = "1.3.4"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"