version: "3.0"
services:
  srv-nginx:
    container_name: srv-nginx
    hostname: srv-nginx
    armour:
      labels: 
        - hello
    image: nginx
    extra_hosts:
      - "client-1:172.21.0.2"
    networks:
      srv-net-1:
        ipv4_address: 172.19.0.2
  
      
  client-1:
    container_name: client-1
    hostname: client-1
    armour: 
      labels:
        - "something::hello::service"
    extra_hosts:
      - "srv-nginx:172.19.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      - srv-net-1

networks:
  srv-net-1:
    driver_opts:
      com.docker.network.bridge.name: armour-srv-nginx
    internal: true
    driver: bridge