[package]
name = "armour-api"
version = "0.2.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
armour-lang = { path = "../armour-lang" }

actix = "0.9"
bincode = "1.2"
bson = "0.14"
byteorder = "1.3"
bytes = "0.5"
http = "0.2"
regex = "1.3"
serde = { version = "1.0",  features = ["derive"] }
tokio-util = "0.2"
url = { version = "2.1", features = ["serde"]}
