Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "rust-build"
    vb.memory = 8192
    vb.cpus = 2
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "rust-build"
  config.ssh.insert_key = false
  config.vm.synced_folder "../", "/home/vagrant/rust"
  config.vm.synced_folder "#{ENV['TARGET_DIR']}", "/home/vagrant/rust/armour/target",
                          :owner => 'vagrant',
                          :mount_options => ['dmode=775', 'fmode=775']
  config.vm.synced_folder "#{ENV['TARGET_DIR']}", "/home/vagrant/rust/policy-services/target",
                          :owner => 'vagrant',
                          :mount_options => ['dmode=775', 'fmode=775']
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision :shell, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y install curl build-essential pkg-config openssl libssl-dev capnproto graphviz
  SHELL
end
