#!/usr/bin/env bash
set -e
set -x
# Build rust binaries
if [ ! -d bins ]; then
  mkdir bins
else
  rm -rf bins/*
fi
cd ..
for arg in ${@:2}; do
  cargo build --target-dir "$1" --release -p $arg
  cp $1/release/$arg "$OLDPWD"/bins
done
cd -
# Build the docker image
docker build -t $2 .
docker images
echo "Done"
