Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  config.vm.provider :virtualbox do |vb|
    vb.name = "example"
    vb.memory = 4096
    vb.cpus = 2
  end
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y capnproto
    sudo apt install -y build-essential
    sudo apt-get install -y pkg-config
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    source $HOME/.cargo/env
    sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install openssl
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq libssl-dev
    git clone https://git.research.arm.com/antfox02/armour.git
    cd /home/vagrant/armour
    git checkout v2
    cd rust/v2/armour-master
    cargo build --release
    cd ../armour-proxy
    cargo build --release
    mkdir ~/binaries/
    cp /home/vagrant/armour/rust/v2/target/release/armour-master ~/binaries/
    cp /home/vagrant/armour/rust/v2/target/release/armour-proxy ~/binaries/
    cd /home/vagrant/armour/rust/policy-services/logger
    cargo build --release
    cp /home/vagrant/armour/rust/policy-services/target/release/logger ~/binaries/
  SHELL
end
