Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  config.vm.provider :virtualbox do |vb|
    vb.name = "data"
    vb.memory = 4096
    vb.cpus = 2
  end
  config.vm.provision :docker
end
