version: '3.0'
services:
  digital-dolly:
    build:
      context: ./digital-dolly
      args:
        registry: git.research.arm.com:4567
    environment:
      MQTT_BROKER_HOST: "mqtt-trusted"
      INFLUXDB_HOST: "poc-influxdb.austin.arm.com"
      BLE_TARGET_HR: 00:22:D0:00:02:09
      HR_RUN_FLAG: ""
    volumes:
      - /dev/ttyAMA0:/dev/ttyAMA0
    network_mode: "host"
    privileged: true
    ports:
      - 5000

  hostapd:
    build: ./hostapd
    network_mode: "host"
    cap_add: ["NET_ADMIN"]

  notifications:
    build:
      context: ./notifications
      args:
        registry: git.research.arm.com:4567
    networks:
      notif:
        ipv4_address: 172.39.0.2
    ports:
      - 80:80/tcp

  mongo-web-interface:
    build:
      context: ./mongo-web-interface
      args:
        registry: git.research.arm.com:4567
    environment:
        MONGO_CONN: "mongodb://mongo/Ledger"
        INFLUXDB_HOST: "poc-influxdb.austin.arm.com"
    depends_on:
      - mongo
    networks:
      mongo-web:
        ipv4_address: 172.38.0.2
    ports:
      - 81:81/tcp

  mongo:
    image: mongo
    networks:
      mongo:
        ipv4_address: 172.37.0.2

  cloud-update:
    build: ./cloud_comm
    networks:
      cloud:
        ipv4_address: 172.36.0.2
    ports:
      - 5000

  accounting:
    build: ./accounting
    environment:
      MONGO_CONN: "mongodb://mongo"
    depends_on:
      - mongo
    networks:
      acconuting:
        ipv4_address: 172.35.0.2
    ports:
      - 5000

  context:
    build: ./context
    environment:
      LIGHTS: ""
      PULSE_MIC_NAME: alsa_input.hw_3_0
      MQTT_BROKER_HOST: "mqtt-trusted"
      FAL_MODEL: "falsestor.pb"
      FAL_SENSITIVITY: "0.1"
      FAL_TRIG_LVL: "13"
    cap_add: ["SYS_RAWIO"]
    privileged: true
    networks:
      context:
        ipv4_address: 172.34.0.2
    ports:
      - 5000

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PoC
    volumes:
      - /var/lib/poc-mysql:/var/lib/mysql
      - /mysql-initdb-config:/docker-entrypoint-initdb.d
    networks:
      mysql:
        ipv4_address: 172.33.0.2

  dbread:
    build:
      context: ./dbread
      args:
        registry: git.research.arm.com:4567
    environment:
      DB_CONN: "mysql://dbint:raspberry@mysql:3306/PoC"
    depends_on:
      - mysql
    networks:
      dbr:
        ipv4_address: 172.32.0.2
    ports:
      - 5000

  dbwrite:
    build:
      context: ./dbwrite
      args:
        registry: git.research.arm.com:4567
    environment:
      DB_CONN: "mysql://dbint:raspberry@mysql:3306/PoC"
    depends_on:
      - mysql
    networks:
      dbw:
        ipv4_address: 172.31.0.2
    ports:
      - 5000

  dtp:
    build:
      context: ./dtp
      args:
        registry: git.research.arm.com:4567
    environment:
      PULSE_SERVER: tcp:pulse:4713
    networks:
      dtp:
        ipv4_address: 172.30.0.2
    ports:
      - 5000

  debug:
    build:
      context: ./debug
      args:
        registry: git.research.arm.com:4567
    environment:
      DB_CONN_REGIST: "mysql://dbint:raspberry@mysql:3306/PoC_Registration"
    depends_on:
      - mysql
    networks:
      debug:
        ipv4_address: 172.29.0.2
    ports:
      - 5000

  launch:
    build: ./launch
    environment:
      RUNLEVEL: "debug"
      DB_CONN_REGIST: "mysql://dbint:raspberry@mysql:3306/PoC_Registration"
    depends_on:
      - mysql
    networks:
      launch:
        ipv4_address: 172.28.0.2
    ports:
      - 5000

  mqtt-debug:
    build: ./mosquitto_trusted
    networks:
      mdebug:
        ipv4_address: 172.27.0.2
    ports:
      - 1883:1883
      - 8883
      - 9001

  mqtt-trusted:
    build: ./mosquitto_trusted
    networks:
      trust:
        ipv4_address: 172.26.0.2
    ports:
      - 1883
      - 8883
      - 9001

  mqtt-public:
    build: ./mosquitto_public
    networks:
      public:
        ipv4_address: 172.25.0.2
    ports:
      - 1883
      - 8883
      - 9001

  picolibri:
    build:
      context: ./picolibri
      args:
        registry: git.research.arm.com:4567
    networks:
      colibri:
        ipv4_address: 172.24.0.2
    ports:
      - 5000

  pipharm:
    build:
      context: ./pipharm
      args:
        registry: git.research.arm.com:4567
    networks:
      pharm:
        ipv4_address: 172.23.0.2
    ports:
      - 5000

  pulse:
    build: ./pulse
    cap_add: ["SYS_RAWIO"]
    volumes:
      - /dev/snd:/dev/snd
    privileged: true
    networks:
      pulse:
        ipv4_address: 172.22.0.2
    ports:
      - 4713:4713/tcp

  verify-id:
    build:
      context: ./verify_id
      args:
        registry: git.research.arm.com:4567
    networks:
      verify:
        ipv4_address: 172.21.0.2
    ports:
      - 5000

  on-during-conversation:
    build:
      context: ./on_during_conversation
      args:
        registry: git.research.arm.com:4567
    environment:
      HR_RUN_FLAG: "-O"
    privileged: true
    networks:
      conv:
        ipv4_address: 172.20.0.2
    ports:
      - 5000

  temperature:
    build: ./temperature
    privileged: true
    environment:
      DEVICE: "28*"
    networks:
      temp:
        ipv4_address: 172.19.0.2

  vitals:
    build: ./vitals
    privileged: true
    cap_add: ["NET_ADMIN"]
    volumes:
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      vitals:
        ipv4_address: 172.18.0.2
networks:
  vitals:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: vitals
    ipam:
      config:
        - subnet: 172.18.0.0/28

  temp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: temp
    ipam:
      config:
        - subnet: 172.19.0.0/28

  conv:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: conv
    ipam:
      config:
        - subnet: 172.20.0.0/28

  verify:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: verify
    ipam:
      config:
        - subnet: 172.21.0.0/28

  pulse:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: pulse
    ipam:
      config:
        - subnet: 172.22.0.0/28

  pharm:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: pharm
    ipam:
      config:
        - subnet: 172.23.0.0/28

  colibri:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: colibri
    ipam:
      config:
        - subnet: 172.24.0.0/28

  public:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: public
    ipam:
      config:
        - subnet: 172.25.0.0/28

  trust:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: trust
    ipam:
      config:
        - subnet: 172.26.0.0/28

  mdebug:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mdebug
    ipam:
      config:
        - subnet: 172.27.0.0/28

  launch:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: launch
    ipam:
      config:
        - subnet: 172.28.0.0/28

  debug:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: debug
    ipam:
      config:
        - subnet: 172.29.0.0/28

  dtp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dtp
    ipam:
      config:
        - subnet: 172.30.0.0/28

  dbw:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dbw
    ipam:
      config:
        - subnet: 172.31.0.0/28

  dbr:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dbr
    ipam:
      config:
        - subnet: 172.32.0.0/28

  mysql:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mysql
    ipam:
      config:
        - subnet: 172.33.0.0/28

  context:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: context
    ipam:
      config:
        - subnet: 172.34.0.0/28

  accounting:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: accounting
    ipam:
      config:
        - subnet: 172.35.0.0/28

  cloud:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cloud
    ipam:
      config:
        - subnet: 172.36.0.0/28

  mongo:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mongo
    ipam:
      config:
        - subnet: 172.37.0.0/28

  mongo-web:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mongo-web
    ipam:
      config:
        - subnet: 172.38.0.0/28

  notif:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: notif
    ipam:
      config:
        - subnet: 172.39.0.0/28
