Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "armour-examples"
    vb.memory = 4096
    vb.cpus = 1
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 8088, host: 8088
  config.vm.network "forwarded_port", guest: 6000, host: 8092
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision "file", source: "../src", destination: "$HOME/src"
  config.vm.provision "file", source: ".", destination: "$HOME/examples"
  config.vm.provision "shell", inline: <<-SHELL
    wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
    sudo apt-get update
    sudo apt-get install -y capnproto build-essential pkg-config openssl libssl-dev mongodb-org
  SHELL
end
