FROM rust:1.31

EXPOSE 8080
COPY proto /usr/src/armour/
RUN apt-get update
RUN apt-get -y install curl screen
RUN apt-get -y install python3-pip
RUN pip3 install Flask requests

WORKDIR /usr/src/armour

CMD ["tail", "-f", "/dev/null"]
