Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "build-musl"
    vb.memory = 8192
    vb.cpus = 2
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "build-musl"
  config.ssh.insert_key = false
  config.vm.synced_folder ENV['ARMOUR_TARGET_DIR'], "/home/vagrant/armour-target"
  config.vm.synced_folder "../", "/home/vagrant/rust"
  config.vm.provision :docker
  config.vm.provision :shell, path: "rustup.sh"
end

