[package]
name = "armour-launch"
version = "0.1.0"
authors = ["Anthony Fox <anthony.fox@arm.com>"]
edition = "2018"

[dependencies]
armour-api = { path = "../armour-api" }
armour-compose = { path = "../armour-compose" }
docker-api = { path = "../docker-api" }

actix-rt = "1.1"
awc = "1.0"
bytes = "0.5"
clap = "2.33"
futures = "0.3"
serde_yaml = "0.8"