Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "armour-examples-multi-host"
    vb.memory = 4096
    vb.cpus = 1
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 8090, host: 8090
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision "file", source: "../../src", destination: "$HOME/src"
  config.vm.provision "file", source: "..", destination: "$HOME/examples"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y capnproto build-essential pkg-config openssl libssl-dev
  SHELL
end
