[package]
name = "iptables-server"
version = "0.1.0"
authors = ["guspet02 <gpetri@irif.fr>"]
edition = "2018"
build = "../build.rs"

[lib]
name = "iptables_lib"
path = "../iptables-lib/lib.rs"

[[bin]]
name = "iptables-server"
path = "src/main.rs"


[build-dependencies]
capnpc = "0.9.5"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
tokio-uds = "0.2.5"
capnp = "0.9.5"
capnp-rpc = "0.9.0"
iptables = "0.2"
nix = "0.14.0"
