[workspace]

members = [
    "armour-api",
    "armour-compose",
    "armour-utils",
    "armour-launch",
    "armour-lang",
    "armour-proxy",
    "armour-master",
    "armour-control",
]

[profile.release]
opt-level = "s"
lto = true