### -*- restclient -*-
###
POST http://127.0.0.1:8088/master/on-board
Content-Type: application/json

{
        "host": "http://localhost",
        "master": "armour::master-1",
        "credentials": "no-creds"
}

###
POST http://127.0.0.1:8088/service/on-board
Content-Type: application/json

{
  "service": "armour::service-1",
  "master": "armour::master-one"
}

###
POST http://127.0.0.1:8088/policy/update
Content-Type: application/json

{
  "label":"no-service",
  "policy":{
    "AllowAll": "HTTP"
  },
  "labels":{
    "a": ["b::c"],
    "d": ["e::f::g"]
  }
}

###
POST http://127.0.0.1:8088/policy/update
Content-Type: application/json

{
  "label":"hello::egress",
  "policy":{
    "Bincode": 
    "H4sIAAAAAAAE/42U0W7bMAxF5a7LNmAbsA3Yhv3D3ge9FgP2vB8wXEdNgjqWaykt+vflsXMTu2jTBrqWSZG8JEWncONvMW6uiatV6N8fpTLF+vrNXmY742H4amBVTRPvyj6kbI+bne0fTC2PPtwgvjMVq6vum1gtEcV8jt6wrHL4aPsnwy8D61/O3f8wBPV+127srVyHahl6ZUGUCRcijhwTbBrckchUAdNnrA0p995f9XFb7vLVH4Vhn3qY4bgKEWCB6vfj4NMSZVTD+ANzw6y2OrZtqPMmtrJlnxQGnzm5oQjOEGpIdHKOxkAR0uUI4zfTsi4OJPtSc1QkdoBZzWPAtCbCIh9DMzJIyhIqeo7rOEbeMxYkiY5zDc3FJJV2t70MvdjZAR414XlxaFQggzLlVHmzhm5DXsclbvizy8Um8i06QEpfeDHM3Lsqr3Ey/cD9lDPnyonuIMteieeIBkBF/3i3CirvmzC7bLVp/4kosnN4qq9/V9bR5P3dpgtEGiCyQp2YfZKpi20KUB+LSIiPCBcWi0iygva76Vi6zhT629CX+xSx5hTLly8Wq5+YG8Zej5l5/9LwJ3XWDb0gd4vhXtNF7AYU0L+ui+q8Spp10/6BUh6+fsJiqi6caP7BnsGTvZJRb+1ic6E7WVh0DAT0AD2VnL6YAx/mABdytahubf+pyuH5EpmCsxMlDecPeXs0pz0GAAA="
  },
  "labels": {}
}

###
GET http://127.0.0.1:8088/policy/query
Content-Type: application/json

{
  "label":"no-service"
}


###
DELETE http://127.0.0.1:8088/policy/drop
Content-Type: application/json

{
  "label":"no-service"
}

###
DELETE http://127.0.0.1:8088/policy/drop-all