### armour-master:> myproxy: launch log

### succeed
GET http://localhost:8090/master/name HTTP/1.1

### succeed
GET http://localhost:8090/master/proxies HTTP/1.1

### succeed
GET http://localhost:8090/policy/query HTTP/1.1
content-type: application/json

"master::myproxy"

### fail (protocol not set in policy)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::myproxy",
  "policy": {
    "Bincode": "H4sIAAAAAAAE/43FMQ0AAACDsCXz75kHAfTpdC8BFkdTsjQAAAA="
  }
}

### fail (wrong master)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "other::myproxy",
  "policy": {
    "AllowAll": "HTTP"
  }
}

### fail (wrong proxy)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::other",
  "policy": {
    "AllowAll": "HTTP"
  }
}

### fail (wrong label)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::myproxy::extra",
  "policy": {
    "AllowAll": "HTTP"
  }
}

### fail (not valid base64)
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::myproxy",
  "policy": {
    "Bincode": "AA="
  }
}

### succeed
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::*",
  "policy": {
    "DenyAll": "TCP"
  }
}

### succeed
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::myproxy",
  "policy": {
    "AllowAll": "HTTP"
  }
}

### succeed
POST http://localhost:8090/policy/update HTTP/1.1
content-type: application/json

{
  "label": "master::myproxy",
  "policy": {
    "Bincode": 
    "H4sIAAAAAAAE/7WV247UMAyGUw7LQYDEQSDxDtyj3O4Nl4gXqEonuzOi0wxtCuINeSz8JXUnKd3dqx3FTePYv387bqYy6XeRJtP562s3PD2v6tG3Px7Oa6ZHPETeiTCarvO/67Y7uD7Up+ZP55vdM9l4IsKYVQR4IGtEJvNSHu9FGCmotSVIbvkGM5FL3/euDQffW9tPx+9u0ATAeysWjK+JhQAu5mrGvGKGRxIwoM5q14TG2s71eKBgE+F9CYCVGjDfCF1pNpWm0sS6DW4M9eB+TjITWistKrDAJKAWXeK5F6KAyEeZGV9COH1LCNZO/UGw6r1rdm5YYopZBiyrONgGKAc3kMgVGLyK5saMYbD2avDHegpXn5Ubc+4xGxtTaQAsjPw+rcHzFNWoJeIHsWYUubWbp5klphAxCV20BIEJeMqTJFQXPBG1d/IOw6oOXpGYEYBaHlHynHBgfYbeansOEFdte3oAO3RQ0Q65XPJdNzssEDxaDWbQaII0ilYGTE2vKOjRhb3f4QYQs7pI+ylS/FJfYyBSuJ+asMdJ9DH2ljP7ikR1WKu9Eg8eTRRVVcq3+ErGk+9HR4HPocbH0dFEmnonJZrJ3NoxNGEa88iZ++xtDKFplb+zRrESg9ENv9xQz5cZFLDFdFZdyDsQiLxGOuv7rQTJLe8+8vwQl+tn+4tYMYNNEjCgzkoa5H7uN41e1q8t/h+qCgoiz0UYmn/z36W4mGoX3dIZi632RMmhLP9irBzWp9WWlPW4OGiES3HrS67YJCdmKq5CYRAc17FW1LZiaf57ue71vcyvJEyPVzfXNW7fUsu4X+KXJKPBP/M1Pms/CAAA"
  }
}
