Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "armour-examples"
    vb.memory = 4096
    vb.cpus = 1
  end
  config.vm.box = "ubuntu/focal64"
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git capnproto build-essential pkg-config
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    source $HOME/.cargo/env
    sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install openssl
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq libssl-dev
    rustup toolchain install 1.45.2
    rustup override set 1.45.2
    git clone -b laurent-sandbox https://git.research.arm.com/antfox02/armour.git
    sudo apt-get update
    wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
  SHELL
end