[package]
name = "server"
version = "0.1.0"
authors = ["Basma El Gaabouri <basma.elgaabouri@arm.com>"]
edition = "2018"

[dependencies]
armour-compose = { path = "../armour-compose" }
actix-web = "2.0"
actix-rt = "1.0"
serde_json = "1.0"
actix = "0.9.0"
actix-web-actors = "2.0.0"