version: "3.0"
services:
  sozu:
    container_name: sozu
    hostname: sozu
    image: "clevercloud/sozu"
    ports:
      - 8000:80
    networks:
      sozu-net:
        ipv4_address: 172.25.0.2
    extra_hosts:
      - "srv-nginx:172.19.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    depends_on:
      - srv-nginx2
      - srv-arm
    volumes:
      - ./sozu/socket:/var/run/sozu
      - ./sozu:/usr/local/etc/sozu/
    command: start -c /usr/local/etc/sozu/config.toml

  envoy:
    container_name: envoy
    hostname: envoy
    image: "envoy"
    build: ./envoy
    ports:
      - 8000:10000
      - 9901:9901
    extra_hosts:
      - "srv-nginx:172.19.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    networks:
      envoy-net:
        ipv4_address: 172.23.0.2
    depends_on:
      - srv-nginx3
      - srv-arm
    volumes:
      - ./envoy/:/etc/envoy/

  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    build: ./nginx
    ports:
      - 8080:8080
    extra_hosts:
      - "srv-nginx:172.19.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    networks:
      nginx-net:
        ipv4_address: 172.24.0.2

  srv-nginx:
    container_name: srv-nginx
    hostname: srv-nginx
    image: nginx
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
      - "client-1:172.21.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
      - "client-2:172.22.0.2"
    networks:
      srv-net-1:
        ipv4_address: 172.19.0.2

  srv-nginx2:
    container_name: srv-nginx2
    hostname: srv-nginx2
    image: nginx
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    networks:
      srv-net-2:
        ipv4_address: 172.20.0.2

  srv-nginx3:
    container_name: srv-nginx3
    hostname: srv-nginx3
    image: nginx
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    networks:
      srv-net-3:
        ipv4_address: 172.26.0.2
  srv-nginx4:
    container_name: srv-nginx4
    hostname: srv-nginx4
    image: nginx
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    networks:
      srv-net-4:
        ipv4_address: 172.27.0.2
  srv-arm:
    container_name: srv-arm
    hostname: srv-arm
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-nginx:172.19.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
      - "client-3:172.31.0.2"
      - "client-4:172.29.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    command: ./arm-service -o 81
    networks:
      srv-net-5:
        ipv4_address: 172.30.0.2

  client-1:
    container_name: client-1
    hostname: client-1
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-nginx:172.19.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
      - "client-2:172.22.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-1:
        ipv4_address: 172.21.0.2

  client-2:
    container_name: client-2
    hostname: client-2
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-nginx:172.19.0.2"
      - "client-1:172.21.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-2:
        ipv4_address: 172.22.0.2

  client-3:
    container_name: client-3
    hostname: client-3
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-nginx:172.19.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
      - "client-2:172.22.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-3:
        ipv4_address: 172.31.0.2

  client-4:
    container_name: client-4
    hostname: client-4
    extra_hosts:
      - "sozu:172.25.0.2"
      - "localho.st:172.25.0.2"
      - "nginx-proxy:172.24.0.2"
      - "envoy:172.23.0.2"
      - "srv-nginx:172.19.0.2"
      - "client-1:172.21.0.2"
      - "srv-nginx4:172.27.0.2"
      - "srv-nginx2:172.20.0.2"
      - "srv-nginx3:172.26.0.2"
      - "srv-arm:172.30.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-4:
        ipv4_address: 172.29.0.2
networks:
  srv-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/28

  srv-net-2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-2
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/28

  cl-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/28

  cl-net-2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-2
    internal: true
    ipam:
      config:
        - subnet: 172.22.0.0/28

  envoy-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: envoy-net
    internal: true
    ipam:
      config:
        - subnet: 172.23.0.0/28

  nginx-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: nginx-net
    internal: true
    ipam:
      config:
        - subnet: 172.24.0.0/28

  sozu-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sozu-net
    internal: true
    ipam:
      config:
        - subnet: 172.25.0.0/28

  srv-net-3:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-3
    internal: true
    ipam:
      config:
        - subnet: 172.26.0.0/28

  srv-net-4:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-4
    internal: true
    ipam:
      config:
        - subnet: 172.27.0.0/28

  cl-net-3:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-3
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/28

  cl-net-4:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-4
    internal: true
    ipam:
      config:
        - subnet: 172.29.0.0/28

  srv-net-5:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-5
    internal: true
    ipam:
      config:
        - subnet: 172.30.0.0/28
