version: "3.0"
services:
  srv-nginx:
    container_name: srv-nginx
    hostname: srv-nginx
    image: nginx
    extra_hosts:
      - "localho.st:private-ip"
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
    networks:
      srv-net-1:
        ipv4_address: 172.19.0.2

  srv-arm:
    container_name: srv-arm
    hostname: srv-arm
    extra_hosts:
      - "localho.st:private-ip"
      - "srv-nginx:172.19.0.2"
      - "client-1:172.21.0.2"
      - "client-2:172.22.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    command: ./arm-service -o 81
    networks:
      srv-net-2:
        ipv4_address: 172.20.0.2

  client-1:
    container_name: client-1
    hostname: client-1
    extra_hosts:
      - "localho.st:private-ip"
      - "srv-nginx:172.19.0.2"
      - "srv-arm:172.20.0.2"
      - "client-2:172.22.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-1:
        ipv4_address: 172.21.0.2

  client-2:
    container_name: client-2
    hostname: client-2
    extra_hosts:
      - "localho.st:172.25.0.2"
      - "srv-nginx:172.19.0.2"
      - "client-1:172.21.0.2"
      - "srv-arm:172.20.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-2:
        ipv4_address: 172.22.0.2
networks:
  srv-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/28

  srv-net-2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-2
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/28

  cl-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/28

  cl-net-2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-2
    internal: true
    ipam:
      config:
        - subnet: 172.22.0.0/28
