version: "3.0"
services:
  srv-nginx:
    container_name: srv-nginx
    hostname: srv-nginx
    image: nginx
    extra_hosts:
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
    networks:
      srv-net-1:
        ipv4_address: 172.19.0.2

  srv-arm:
    container_name: srv-arm
    hostname: srv-arm
    extra_hosts:
      - "srv-nginx:172.19.0.2"
      - "client-1:172.21.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    command: ./arm-service -o 81
    networks:
      srv-net-2:
        ipv4_address: 172.20.0.2
      
  client-1:
    container_name: client-1
    hostname: client-1
    extra_hosts:
      - "srv-nginx:172.19.0.2"
      - "srv-arm:172.20.0.2"
      - "srv-apache:172.23.0.2"
      - "srv-lighttpd:172.24.0.2"
      - "srv-cherokee:172.25.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    image: client-python
    networks:
      cl-net-1:
        ipv4_address: 172.21.0.2
  srv-apache:
    container_name: srv-apache
    hostname: srv-apache
    image: httpd:latest
    extra_hosts:
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
    networks:
      srv-net-3:
        ipv4_address: 172.23.0.2

  srv-lighttpd:
    container_name: srv-lighttpd
    hostname: srv-lighttpd
    image: sebp/lighttpd
    volumes:
      - /home/ec2-user/containers/lighttpd/:/var/www/localhost/htdocs
    extra_hosts:
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
    networks:
      srv-net-4:
        ipv4_address: 172.24.0.2

  srv-cherokee:
    container_name: srv-cherokee
    hostname: srv-cherokee
    image: managedkaos/cherokee
    extra_hosts:
      - "srv-arm:172.20.0.2"
      - "client-1:172.21.0.2"
    networks:
      srv-net-5:
        ipv4_address: 172.25.0.2
networks:
  srv-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.19.0.0/28

  srv-net-2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-2
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/28
  
  srv-net-3:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-3
    internal: true
    ipam:
      config:
        - subnet: 172.23.0.0/28

  srv-net-4:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-4
    internal: true
    ipam:
      config:
        - subnet: 172.24.0.0/28

  srv-net-5:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: srv-net-5
    internal: true
    ipam:
      config:
        - subnet: 172.25.0.0/28

  cl-net-1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: cl-net-1
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/28
