[workspace]

members = [
    "armour-api",
    "armour-compose",
    "armour-utils",
    "armour-launch",
    "armour-lang",
    "armour-proxy",
    "armour-master",
    "armour-control",
    "armour-serde",
    "armour-ctl",
    "docker-api"
]

[profile.release]
opt-level = 3
lto = true
