version: '2.2'

networks:
  test_net:
    driver: bridge

services:

  sut:
    image: reports
    entrypoint: node_modules/mocha/bin/mocha --ui tdd test/test.js 
    environment:
      - DATABASE_NAME=reports_test_db
    networks:
      - test_net
    depends_on:
      - reports

  reports:
    build: .
    image: reports
    environment:
      - DATABASE_NAME=reports_test_db
    networks:
      - test_net
    depends_on:
      - database

  database:
    image: mongo:3.6
    networks:
      - test_net

