[package]
name = "docker-server"
version = "0.1.0"
authors = ["guspet02 <gpetri@irif.fr>"]
edition = "2018"
build = "../build.rs"

[lib]
name = "docker_lib"
path = "../docker-lib/lib.rs"

[[bin]]
name = "docker-server"
path = "src/main.rs"


[build-dependencies]
capnpc = "0.9.5"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
tokio-executor = "0.1"
tokio-reactor = "0.1"
tokio-current-thread = "0.1"
tokio-threadpool = "0.1"
tokio-timer = "0.2"
tokio-uds = "0.2.5"
capnp = "0.9.5"
capnp-rpc = "0.9.0"
shiplift = "0.5.0"
log = "0.4.6"
controlplane_lib = { path = "../../control-plane/control-plane-lib" }
serde = "1.0.92"